config/routes.rb
Rails.application.routes.draw do
  resources :candidates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name, presence: true
  validates :party, presence: true
  validates :age, presence: true
  validates :politics, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = Candidate.all
  end
  
  def show
    @candidate = Candidate.find_by(id: params[:id])
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(condidate_params)

    if @candidate.save
      flash[:notice] = "創建成功"
      redirect_to '/candidates'
    else
      #NG
      render :new
    end
  end

  def edit
    @candidate = Candidate.find_by(id: params[:id])
  end

  def update
    @candidate = Candidate.find_by(id: params[:id])
    if @candidate.update(condidate_params)
      flash[:notice] = "更新成功"
      redirect_to '/candidates'
    else
      render :edit
    end
  end

  def destroy
    @candidate = Candidate.find_by(id: params[:id])
    @candidate.destroy
    flash[:notice] = "刪除成功"
    redirect_to '/candidates'
  end


  private
  def condidate_params
    params.require(:candidate).permit(:name, :party, :age, :politics)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<% if @candidate.errors.any? %>
  <ul>
    <% @candidate.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@candidate) do |f| %>

<div class="form_field">
  <%= f.label :name, "姓名" %>
  <%= f.text_field :name %>
</div>

<div class="form_field">
  <%= f.label :party, "政黨" %>
  <%= f.text_field :party %>
</div>

<div class="form_field">
  <%= f.label :age, "年齡" %>
  <%= f.text_field :age %>
</div>

<div class="form_field">
  <%= f.label :politics, "政見" %>
  <%= f.text_area :politics %>
</div>

<div class="form_field"><%= f.submit %></div>

<% end %>

app/views/candidates/index.html.erb
<%= flash[:notice] %>
<br>
<%= link_to "新增候選人", new_candidate_path %>
<h1>候選人列表</h1>

<table>
  <tr>
    <td>姓名</td>
    <td>政黨</td>
    <td>年齡</td>
    <td>Action</td>
  </tr>

  <% @candidates.each do |candidate| %>
    <tr>
      <td><%= link_to candidate.name, candidate_path(candidate.id) %></td>
      <td><%= candidate.party %></td>
      <td><%= candidate.age %></td>
      <td><%= link_to "編輯", edit_candidate_path(candidate.id) %></td>
      <td><%= link_to "刪除", candidate_path(candidate.id), method: "delete", data: { confirm: "確定要刪除嗎？" } %></td>
    </tr>
  <% end %>

</table>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<% if @candidate.errors.any? %>
  <ul>
    <% @candidate.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@candidate) do |f| %>

<div class="form_field">
  <%= f.label :name, "姓名" %>
  <%= f.text_field :name %>
</div>

<div class="form_field">
  <%= f.label :party, "政黨" %>
  <%= f.text_field :party %>
</div>

<div class="form_field">
  <%= f.label :age, "年齡" %>
  <%= f.text_field :age %>
</div>

<div class="form_field">
  <%= f.label :politics, "政見" %>
  <%= f.text_area :politics %>
</div>

<div class="form_field"><%= f.submit %></div>

<% end %>

app/views/candidates/show.html.erb
<% if @candidate %>

  <h1><%= @candidate.name %></h1>
  <ul>
    <li>年齡：<%= @candidate.age %></li>
    <li>政黨：<%= @candidate.party %></li>
  </ul>
  <h2>政見</h2>
  <p><%= @candidate.politics %></p>

<% else %>
  <h1>找不到此頁面！</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>